# -*- coding: utf-8 -*-
"""rag-pdf-question-answering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19m84LafcXERkzdKwJMiJY2UH6Ps6SOof
"""

pip install langchain langchain-core langchain-community pypdf pymupdf sentence-transformers chromadb

import os
from langchain_community.document_loaders.pdf import PyPDFLoader

def load_all_pdfs():
  folder_path = "data/pdfs"
  num_docs = 0
  all_docs = []

  for filename in os.listdir(folder_path):
    if filename.lower().endswith('.pdf'):
      pdf_path = os.path.join(folder_path, filename)
      loader = PyPDFLoader(pdf_path)
      doc = loader.load()
      all_docs.extend(doc)
      num_docs += 1

  print("total pdfs:", num_docs)
  print("total pages:",len(all_docs))
  return all_docs
all_pdf_documents = load_all_pdfs()
print(all_pdf_documents)

print(type(all_pdf_documents))

!pip install langchain_text_splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

def split_docs(documents , chunk_size=500 , chunk_overlap=50):
  text_splitter = RecursiveCharacterTextSplitter(
      chunk_size=chunk_size,
      chunk_overlap=chunk_overlap
  )
  chunk_docs = text_splitter.split_documents(documents)
  print(chunk_docs)
  return chunk_docs

chunks = split_docs(all_pdf_documents)
print(len(chunks))
chunks[50]

from sentence_transformers import SentenceTransformer

class EmbeddingManager:
    def __init__(self, model_name="all-MiniLM-L6-v2"):

        self.model_name = model_name
        print("loading model...", self.model_name)
        self.model = SentenceTransformer(model_name)
        print("embedding dimensions=", self.model.get_embedding_dimension())

    def generate_embeddings(self, text):
        embeddings = self.model.encode(text, show_progress_bar=True)
        print("embedding shape:", embeddings.shape)
        return embeddings

embedding_manager = EmbeddingManager()

import chromadb
import uuid

class VectorStoreManager:
  def __init__(self, persist_directory= "data/vector_store", collection_name="pdf_documents"):
    self.collection_name=collection_name
    self.persist_directory=persist_directory
    self.collection=None
    self.client = None

    self._initialize_store()

  def _initialize_store(self):
    os.makedirs(self.persist_directory, exist_ok=True)
#creating client
    self.client = chromadb.PersistentClient(path=self.persist_directory)
#creating Collection

    self.collection= self.client.get_or_create_collection(
       name=self.collection_name,
       metadata={"description":"Vector Store Collection for pdf embedding in RAG"}
    )
    print("Initilized the vector store collection", self.collection_name)
    print("docs in Collcetion ", self.collection.count())

  def add_documents(self, documents , embeddings):
    if len(documents) != len(embeddings):
      raise ValueError("Number of documents does not match with the num of Embeddings")

    ids=[]
    all_metadata=[]
    document_content=[]
    embeddings_list = []

    for i , (doc , embedding) in enumerate(zip(documents,embeddings)):
      doc_id = f"doc_{uuid.uuid4()}"
      ids.append(doc_id)

      metadata=dict(doc.metadata)
      metadata["doc_index"]=i
      metadata["content_length"] = len(doc.page_content)
      all_metadata.append(metadata)

      document_content.append(doc.page_content)
      embeddings_list.append(embedding.tolist())

      self.collection.add(
          ids=ids,
          documents=document_content,
          metadatas=all_metadata,
          embeddings=embeddings_list
      )
    print("Total document add in vector store:",len(document_content))
    print("Docs in Collection :", self.collection.count())

vector_store = VectorStoreManager()

# data => documents => chunks => embeddings => store in vector store

texts = [doc.page_content for doc in chunks]

embeddings = embedding_manager.generate_embeddings(texts)

vector_store.add_documents(chunks, embeddings)

from sklearn.metrics.pairwise import cosine_similarity

class RAGRetriever:
    def __init__(self, embedding_manager, vector_store):
        self.embedding_manager = embedding_manager
        self.vector_store = vector_store

    def retrieve(self, query, top_k=5, score_threshold=0.0):
        # query => embedding
        query_embeddings = self.embedding_manager.generate_embeddings([query])[0]

        # semantic search
        results = self.vector_store.collection.query(
            query_embeddings=[query_embeddings.tolist()],
            n_results=top_k
        )

        # cosine similarity
        retrieved_docs = []

        if results["documents"] and results["documents"][0]:
            ids = results["ids"][0]
            metadatas = results["metadatas"][0]
            documents = results["documents"][0]
            distances = results["distances"][0]

            for i, (doc_id, metadata, document, distance) in enumerate(zip(ids, metadatas, documents, distances)):
                similarity_score = 1 - distance
                if similarity_score >= score_threshold:
                    retrieved_docs.append({
                        "id": doc_id,
                        "document": document,
                        "metadata": metadata,
                        "distance": distance,
                        "similarity_score": similarity_score,
                        "rank": i + 1
                    })

            print(f"retrieved {len(retrieved_docs)} documents")

        else:
            print("no document found")

        return retrieved_docs

rag_retriever = RAGRetriever(
    embedding_manager,
    vector_store
)

print("Retriever created successfully ✅")

reg_retriever.retrieve("how to sholve Ratio Questions")

!pip install langchain-groq

API_GROQ_KEY= "your api"

from langchain_groq import ChatGroq

# llm = ChatGroq(
#     grok_api_key = API_GROQ_KEY,
#     model = "qwen/qwen3-32b",
#     temperature=0.1,
#     max_tokens=1024
# )

llm = ChatGroq(
    groq_api_key=API_GROQ_KEY,
    model="qwen/qwen3-32b",
    temperature=0.1,
    max_tokens=1024
)

# generate our retrieval-augmented output
def generate_output(query, retriever, llm, top_k=3):
    results = retriever.retrieve(query, top_k)

    context = "\n".join([doc["document"] for doc in results]) if results else ""

    if not context:
        print("we found no relevant context for the given query")

    # prompt => context + query
    prompt = f""" use given context to generate the answer for the query
                Context: {context},
                Query: {query}
            """

    response = llm.invoke([prompt]) # expecting a list as prompt
    return response.content

answer = generate_output(
    "how to solve ratio questions?",
    rag_retriever,
    llm
)

print(answer)